config_dict = {
    "Admission": {
        "path": "data/admission.csv",
        "Full dataset": {
            "auth_methods": {
                None: {},
                "relative": {},
                "absolute": {},
                "product": {},
                "harmonic_0.01": {},
                "harmonic_0.25": {},
                "harmonic_0.5": {},
                "harmonic_0.75": {},
                "harmonic_1.0": {},
                "harmonic_1.25": {},
                "harmonic_1.5": {},
                "harmonic_1.75": {},
                "harmonic_2.0": {},
            },
        },
    },
    "Churn": {
        "path": "data/churn.csv",
        "Full dataset": {
            "auth_methods": {
                None: {},
                "relative": {},
                "absolute": {},
                "product": {},
                "harmonic_0.01": {},
                "harmonic_0.25": {},
                "harmonic_0.5": {},
                "harmonic_0.75": {},
                "harmonic_1.0": {},
                "harmonic_1.25": {},
                "harmonic_1.5": {},
                "harmonic_1.75": {},
                "harmonic_2.0": {},
            },
        },
    },
    "Churn": {
        "path": "data/fraud.csv",
        "Full dataset": {
            "auth_methods": {
                None: {},
                "relative": {},
                "absolute": {},
                "product": {},
                "harmonic_0.01": {},
                "harmonic_0.25": {},
                "harmonic_0.5": {},
                "harmonic_0.75": {},
                "harmonic_1.0": {},
                "harmonic_1.25": {},
                "harmonic_1.5": {},
                "harmonic_1.75": {},
                "harmonic_2.0": {},
            },
        },
    },
    "Churn": {
        "path": "data/COMPAS.csv",
        "Full dataset": {
            "auth_methods": {
                None: {},
                "relative": {},
                "absolute": {},
                "product": {},
                "harmonic_0.01": {},
                "harmonic_0.25": {},
                "harmonic_0.5": {},
                "harmonic_0.75": {},
                "harmonic_1.0": {},
                "harmonic_1.25": {},
                "harmonic_1.5": {},
                "harmonic_1.75": {},
                "harmonic_2.0": {},
            },
        },
    },
}
