config_dict = {
    "Admission": {
        "path": "data/admission.csv",
        "Full dataset": {
            "auth_methods": {
                None: {},
                # "relative": {},
                # "absolute": {},
                # "product": {},
                # "harmonic_0.1": {},
                # "harmonic_0.2": {},
                # "harmonic_0.3": {},
                # "harmonic_0.4": {},
                # "harmonic_0.5": {},
                # "harmonic_0.6": {},
                # "harmonic_0.7": {},
                # "harmonic_0.8": {},
                # "harmonic_0.9": {},
                # "harmonic_1.0": {},
                # "harmonic_1.1": {},
                # "harmonic_1.2": {},
                # "harmonic_1.3": {},
                # "harmonic_1.4": {},
                # "harmonic_1.5": {},
                # "harmonic_1.6": {},
                # "harmonic_1.7": {},
                # "harmonic_1.8": {},
                # "harmonic_1.9": {},
                # "harmonic_2.0": {},
            },
        },
        # "Consistent subset": {
        #     "auth_methods": {
        #         None: {},
        #         "relative": {},
        #         "absolute": {},
        #         "product": {},
        #         "harmonic_0.1": {},
        #         "harmonic_0.2": {},
        #         "harmonic_0.3": {},
        #         "harmonic_0.4": {},
        #         "harmonic_0.5": {},
        #         "harmonic_0.6": {},
        #         "harmonic_0.7": {},
        #         "harmonic_0.8": {},
        #         "harmonic_0.9": {},
        #         "harmonic_1.0": {},
        #         "harmonic_1.1": {},
        #         "harmonic_1.2": {},
        #         "harmonic_1.3": {},
        #         "harmonic_1.4": {},
        #         "harmonic_1.5": {},
        #         "harmonic_1.6": {},
        #         "harmonic_1.7": {},
        #         "harmonic_1.8": {},
        #         "harmonic_1.9": {},
        #         "harmonic_2.0": {},
        #     },
        # },
    },
    # "Churn": {
    #     "path": "data/churn.csv",
    #     "Full dataset": {
    #         "auth_methods": {
    #             None: {},
    #             "relative": {},
    #             "absolute": {},
    #             "product": {},
    #             "harmonic_0.1": {},
    #             "harmonic_0.2": {},
    #             "harmonic_0.3": {},
    #             "harmonic_0.4": {},
    #             "harmonic_0.5": {},
    #             "harmonic_0.6": {},
    #             "harmonic_0.7": {},
    #             "harmonic_0.8": {},
    #             "harmonic_0.9": {},
    #             "harmonic_1.0": {},
    #             "harmonic_1.1": {},
    #             "harmonic_1.2": {},
    #             "harmonic_1.3": {},
    #             "harmonic_1.4": {},
    #             "harmonic_1.5": {},
    #             "harmonic_1.6": {},
    #             "harmonic_1.7": {},
    #             "harmonic_1.8": {},
    #             "harmonic_1.9": {},
    #             "harmonic_2.0": {},
    #         },
    #     },
    # },
}
