config_dict = {
    "Admission": {
        "path": "data/admission.csv",
        "Full dataset": {
            "auth_methods": {
                # "default": {},
                # "relative": {},
                # "absolute": {},
                # "product": {},
                "harmonic_0.01": {},
                "harmonic_0.25": {},
                "harmonic_0.5": {},
                "harmonic_0.75": {},
                "harmonic_1.0": {},
                "harmonic_1.25": {},
                "harmonic_1.5": {},
                "harmonic_1.75": {},
                "harmonic_2.0": {},
                "harmonic_2.5": {},
                "harmonic_3.0": {},
                "harmonic_3.5": {},
                "harmonic_4.0": {},
                "harmonic_4.5": {},
                "harmonic_5.0": {},
                "harmonic_6.0": {},
                "harmonic_7.0": {},
                "harmonic_8.0": {},
                "harmonic_9.0": {},
                "harmonic_10.0": {},
            },
        },
    },
    # "Churn": {
    #     "path": "data/churn.csv",
    #     "Full dataset": {
    #         "auth_methods": {
    #             "default": {},
    #             "relative": {},
    #             "absolute": {},
    #             "product": {},
    #             "harmonic_0.01": {},
    #             "harmonic_0.25": {},
    #             "harmonic_0.5": {},
    #             "harmonic_0.75": {},
    #             "harmonic_1.0": {},
    #             "harmonic_1.25": {},
    #             "harmonic_1.5": {},
    #             "harmonic_1.75": {},
    #             "harmonic_2.0": {},
    #         },
    #     },
    # },
    # "Fraud": {
    #     "path": "data/fraud.csv",
    #     "Full dataset": {
    #         "auth_methods": {
    #             "default": {},
    #             "relative": {},
    #             "absolute": {},
    #             "product": {},
    #             "harmonic_0.01": {},
    #             "harmonic_0.25": {},
    #             "harmonic_0.5": {},
    #             "harmonic_0.75": {},
    #             "harmonic_1.0": {},
    #             "harmonic_1.25": {},
    #             "harmonic_1.5": {},
    #             "harmonic_1.75": {},
    #             "harmonic_2.0": {},
    #         },
    #     },
    # },
    # "COMPAS": {
    #     "path": "data/COMPAS.csv",
    #     "Full dataset": {
    #         "auth_methods": {
    #             "default": {},
    #             "relative": {},
    #             "absolute": {},
    #             "product": {},
    #             "harmonic_0.01": {},
    #             "harmonic_0.25": {},
    #             "harmonic_0.5": {},
    #             "harmonic_0.75": {},
    #             "harmonic_1.0": {},
    #             "harmonic_1.25": {},
    #             "harmonic_1.5": {},
    #             "harmonic_1.75": {},
    #             "harmonic_2.0": {},
    #         },
    #     },
    # },
}
